
library(MASS)

args = commandArgs(trailingOnly = TRUE)

con = textConnection(args)
    new_data = read.csv(con)
close(con)
load("compound_0_lda_model.RData")
load("compound_1_lda_model.RData")
load("compound_2_lda_model.RData")
load("compound_3_lda_model.RData")

load("lap_1_lda_model.RData")
load("lap_2_lda_model.RData")
load("lap_3_lda_model.RData")
compound_0_prediction = predict(compound_0_model, new_data)
compound_1_prediction = predict(compound_1_model, new_data)
compound_2_prediction = predict(compound_2_model, new_data)
compound_3_prediction = predict(compound_3_model, new_data)

lap_1_prediction = predict(lap_1_model, new_data)
lap_2_prediction = predict(lap_2_model, new_data)
lap_3_prediction = predict(lap_3_model, new_data)
cat("{\n")
cat("    \"laps\": [ 0, ")
cat(as.character(lap_1_prediction$class), ", ")
cat(as.character(lap_2_prediction$class), ", ")
cat(as.character(lap_3_prediction$class), " ],\n")
cat("    \"compounds\": [ ")
cat("\"", as.character(compound_0_prediction$class), "\"", ", ")
cat("\"", as.character(compound_1_prediction$class), "\"", ", ")
cat("\"", as.character(compound_2_prediction$class), "\"", ", ")
cat("\"", as.character(compound_3_prediction$class), "\"", " ]\n")
cat("}\n")
